### PR TITLE
Add focusable button and optional play label

### PR DESCRIPTION
**Pull request by spacedawwwg**
Pull request makes the play `<button>` a button with a title attribute

Title attribute defaults to `Play video: {ID}`, But can be overwritten with a data attr `data-playlabel` to allow custom/localised descriptive text.

### CODE REVIEW

**Comment by spacedawwwg** [comment]
fixes #9

**Comment by paulirish** [comment]
sorry to make you do this but can you rebase against master?

**Comment by paulirish** [comment]
thx very much for the PR btw

**Comment by spacedawwwg** [comment]
Not a problem, will get it sorted 👍

**Comment by spacedawwwg** [comment]
@paulirish I've built off master branch. Also added a conditional statement around adding the play button to account for the 'progressively enhanced' version which already contains the button

**Comment by spacedawwwg** [comment]
Bonus Youtube SVG icon (and matching `focus` box-shadow styles) added

**Comment by Garbee** [comment]
My only concern here is for usability I wouldn't want the id in the title long-term. That's essentially useless information to users that need it. I think having an attribute for the title of the video to be provided would be best so it is filled with useful content. *However* we haven't built all the attribute handling out yet (on my to-do list for this weekend if I'm not working on actual work things.) 

This looks good to me to get going for the time being. Really nice improvement for accessibility.

**Comment by spacedawwwg** [comment]
> My only concern here is for usability I wouldn't want the id in the title long-term. That's essentially useless information to users that need it. I think having an attribute for the title of the video to be provided would be best so it is filled with useful content. _However_ we haven't built all the attribute handling out yet (on my to-do list for this weekend if I'm not working on actual work things.)
> 
> This looks good to me to get going for the time being. Really nice improvement for accessibility.

ID as the title was just a fallback if a `playlabel` attribute isn't supplied. My thought was rather than have a multitude of generic 'Play Video' labels (if more than one video exists per-page), it at least gives each video some context (albeit a random ID)

**Comment by Garbee** [comment]
Oh fantastic, you already have an attribute there to cover it (I missed that looking at the code during a meeting.) So I just need to make sure the right change event is wired up when I go do my thing.

**Comment by spacedawwwg** [comment]
Any movement on this @Garbee ?

**Comment by Garbee** [comment]
I don't have merge capability. That's all up to @paulirish right now.

**Comment by paulirish** [comment]
@spacedawwwg hey man. i feel bad, especially since we're both named so righteously.

but unfortunately I havent' been able to move forward with this PR.. mostly because it's trying to solve multiple problems at once. It's much easier for me to review and handle them one by one.  

The things you brought up:

* **div to button?** yes. love it. and you caught the `type=button` snafu that #35 missed.
* **playLabel?** i don't love making the video ID human visible. I think a `aria-label` of `"Play"` on the button makes sense but that's about it.
* **use the YT svg?** yes love it. just wanted to address it separately. i'm gonna iterate on #39 for this one.

since you were the first contributor to propose a nice big PR _i'd love to make sure we land some code from you_.  once i merge in #39, do you want to create a new PR to do the div=>button work?

**Comment by spacedawwwg** [comment]
@paulirish Don’t feel bad, man! I got trigger happy early on before all these issues were being raised - sure thing, I’ll cherry pick the accessibility work and rework it into master 👌

**Comment by spacedawwwg** [comment]
closed in favour of https://github.com/paulirish/lite-youtube-embed/pull/46

**Pull request closed without merging**
