### PR TITLE
Actually use progressive enhancement with a link rather than button

### LINKED ISSUE #113: The "Progressive Enhancement" approach does nothing
Maybe instead of a `button` (which requires JS to work) it should be a direct link to the video?

### PR DESCRIPTION
**Pull request by aarongustafson**
Closes #113

### CODE REVIEW

**Comment by aarongustafson** [comment]
Tested: https://lite-youtube-embed-f0314late-paulirish.vercel.app/variants/pe.html

**Review by paulirish — APPROVED** [review]
Yeah this is great. Thanks for the issue and following up with  PR.
Sorry for the delay responding, but I was onboard from the start.

Appreciate it, aaron!

**Comment by aarongustafson** [comment]
Thanks @paulirish! I totally forgot to update the Readme. Do you want me to submit a PR with that update too?

**Comment by paulirish** [comment]
that'd be super great, yeah.

**Pull request merged**
